### ISSUE TITLE
impossible to install from master

### ISSUE THREAD

**Issue by nicolasmsg** [01org/TPM2.0-TSS#366] opened 2017-03-09 21:29 UTC
During make  : 

> test/tpmclient/tpmclient.c: In function ‘TestNV’:
test/tpmclient/tpmclient.c:1930:5: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
     for( i = 0; i < nvAuth.t.size; i++ )
     ^~~
test/tpmclient/tpmclient.c:1933:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
  publicInfo.t.size = sizeof( TPMI_RH_NV_INDEX ) +
  ^~~~~~~~~~
test/tpmclient/tpmclient.c: In function ‘TestHierarchyControl’:
test/tpmclient/tpmclient.c:2159:5: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
     for( i = 0; i < nvAuth.t.size; i++ )
     ^~~
test/tpmclient/tpmclient.c:2162:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
  publicInfo.t.size = sizeof( TPMI_RH_NV_INDEX ) +
  ^~~~~~~~~~
test/tpmclient/tpmclient.c: In function ‘CreatePasswordTestNV’:
test/tpmclient/tpmclient.c:3935:5: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
     for( i = 0; i < nvAuth.t.size; i++ )
     ^~~
test/tpmclient/tpmclient.c:3938:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
  publicInfo.t.size = sizeof( TPMI_RH_NV_INDEX ) +
  ^~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:3148: test/tpmclient/tpmclient.o] Error 1

**Comment by flihp** [comment] 2017-03-09 21:33
What version of GCC are you using? AFAIK newer versions get picky about indentation.

**Comment by nicolasmsg** [comment] 2017-03-09 21:38
I'm using gcc version 6.3.1 20170109 (GCC)

**Comment by flihp** [comment] 2017-03-09 21:57
That'll do it. This is a duplicate of #226 and #229. Only reason I haven't fixed these is that I'm on Debian stable and there aren't GCC 6 packages for it (may be backports?). Looks like stretch has finally been frozen so it may be time for an upgrade.

In the meantime I'll gladly take patches.

**Comment by williamcroberts** [comment] 2017-03-09 23:25
FYI if you just need a build, you can bypass these by setting CFLAGS='-Wnoerror=misleading-indentation' during make

`make CFLAGS='-Wnoerror=misleading-indentation' `

IIUC, you can also set up cflags diring configure time in autotools.

**Comment by flihp** [comment] 2017-03-10 19:26
Good pointer @williamcroberts. I've got an old laptop I'm setting up with stretch on it now. If this issue begins and ends with indentation problems it should be easy enough to fix.

**Comment by flihp** [comment] 2017-03-13 17:27
I pushed a few commits at the end of last week that should resolve this issue. I've tested this using GCC 6 as shipped by Debian testing as well as a build of OpenEmbedded / Yocto using the recipes from meta-measured.

If these fixes don't work for you feel free to re-open this issue or create another.

**Closed by flihp** 2017-03-13 17:27 UTC
Labels: duplicate
